# Generated by Django 5.1.2 on 2024-11-21 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0003_alter_movie_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='biography_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='biography_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='biography_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='biography_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='biography_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='biography_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='genre_name_en',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='genre_name_ru',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='genre_name_uz',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='text_uz',
            field=models.TextField(null=True),
        ),
    ]
